# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-03 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('ejob', models.CharField(max_length=30)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
