# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-03 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deptno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ejob',
            field=models.CharField(blank=True, max_length=30, null=0),
        ),
    ]
