# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-27 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_auto_20200613_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 15, 3, 39, 777512, tzinfo=utc)),
        ),
    ]
